module.exports = {
  trailingComma: 'all',
  singleQuote: true,
  tabWidth: 2,
  semi: true,
  useTabs: false,
  quoteProps: 'consistent',
  arrowParens: 'always',
  printWidth: 90,
  plugins: ['prettier-plugin-tailwindcss', '@trivago/prettier-plugin-sort-imports'],
  importOrder: [
    '^next$',
    '^next/.*$',
    '^react$',
    '^react-.*$',
    '^@/hooks/.*$',
    '^@/hocs/.*$',
    '^@/components/.*$',
    '^@/config/.*$',
    '^@/config/api/.*$',
    '^@/config/helpers/.*$',
    '^@/config/constants/.*$',
    '^@/config/types/.*$',
    '^[./]',
    '.*',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
