// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dealerships": {
            "get": {
                "description": "Returns seeded dealerships available to the inventory dashboard.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dealerships"
                ],
                "summary": "List dealerships",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DealershipListResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    }
                }
            }
        },
        "/dealerships/{dealershipID}/stocks": {
            "get": {
                "description": "Returns paginated inventory stock with search, filters, and enum-constrained sorting.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "List dealership stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dealership ID",
                        "name": "dealershipID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive make/model search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive make filter",
                        "name": "make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive model filter",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "IN_STOCK",
                            "OUT_OF_STOCK"
                        ],
                        "type": "string",
                        "description": "Stock status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Minimum stock age in calendar days",
                        "name": "minAgeDays",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Maximum stock age in calendar days",
                        "name": "maxAgeDays",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Only return in-stock inventory older than 90 days",
                        "name": "agingOnly",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "STOCKED_IN_AT",
                            "MAKE",
                            "MODEL",
                            "MODEL_YEAR",
                            "PRICE",
                            "STATUS"
                        ],
                        "type": "string",
                        "description": "Sort column",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StockListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    }
                }
            }
        },
        "/dealerships/{dealershipID}/stocks/aging": {
            "get": {
                "description": "Returns only in-stock inventory older than 90 calendar days.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "List aging stock",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dealership ID",
                        "name": "dealershipID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive make/model search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive make filter",
                        "name": "make",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Case-insensitive model filter",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "STOCKED_IN_AT",
                            "MAKE",
                            "MODEL",
                            "MODEL_YEAR",
                            "PRICE",
                            "STATUS"
                        ],
                        "type": "string",
                        "description": "Sort column",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "sortOrder",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StockListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    }
                }
            }
        },
        "/dealerships/{dealershipID}/stocks/{stockID}/actions": {
            "post": {
                "description": "Appends a manager action for an in-stock vehicle older than 90 days.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Create stock action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dealership ID",
                        "name": "dealershipID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "stockID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aggregate.CreateInventoryActionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.InventoryActionResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    }
                }
            }
        },
        "/dealerships/{dealershipID}/stocks/{stockID}/history": {
            "get": {
                "description": "Returns merged stock movement and manager action history newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inventory"
                ],
                "summary": "Get stock history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dealership ID",
                        "name": "dealershipID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "stockID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StockHistoryResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    }
                }
            }
        },
        "/dealerships/{dealershipID}/stocks/{stockID}/movements": {
            "post": {
                "description": "Atomically appends a STOCK_IN or STOCK_OUT movement and transitions current stock state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movements"
                ],
                "summary": "Record stock movement",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dealership ID",
                        "name": "dealershipID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stock ID",
                        "name": "stockID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Movement payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/aggregate.CreateStockMovementReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.StockResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ValidationErrResp"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.BaseResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "aggregate.CreateInventoryActionReq": {
            "type": "object",
            "required": [
                "actionType",
                "note"
            ],
            "properties": {
                "actionType": {
                    "enum": [
                        "PRICE_REDUCTION_PLANNED",
                        "TRANSFER_PROPOSED",
                        "MARKETING_CAMPAIGN",
                        "AWAITING_REVIEW",
                        "OTHER"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/constant.InventoryActionType"
                        }
                    ],
                    "example": "AWAITING_REVIEW"
                },
                "note": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 1,
                    "example": "Review this stock item with the sales manager"
                }
            }
        },
        "aggregate.CreateStockMovementReq": {
            "type": "object",
            "required": [
                "movementType",
                "note"
            ],
            "properties": {
                "movementType": {
                    "enum": [
                        "STOCK_IN",
                        "STOCK_OUT"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/constant.StockMovementType"
                        }
                    ],
                    "example": "STOCK_OUT"
                },
                "note": {
                    "type": "string",
                    "maxLength": 500,
                    "minLength": 1,
                    "example": "Vehicle delivered to customer"
                }
            }
        },
        "aggregate.DealershipAggregate": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "aggregate.InventoryActionAggregate": {
            "type": "object",
            "properties": {
                "actionType": {
                    "$ref": "#/definitions/constant.InventoryActionType"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "aggregate.InventoryStockAggregate": {
            "type": "object",
            "properties": {
                "dealershipId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "inventoryAgeDays": {
                    "type": "integer"
                },
                "isAging": {
                    "type": "boolean"
                },
                "latestAction": {
                    "$ref": "#/definitions/aggregate.InventoryActionAggregate"
                },
                "make": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "modelYear": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/constant.StockStatus"
                },
                "stockedInAt": {
                    "type": "string"
                },
                "stockedOutAt": {
                    "type": "string"
                },
                "vehicleId": {
                    "type": "string"
                },
                "vin": {
                    "type": "string"
                }
            }
        },
        "aggregate.InventoryStockListAggregate": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/aggregate.InventoryStockAggregate"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "aggregate.StockHistoryEventAggregate": {
            "type": "object",
            "properties": {
                "actionType": {
                    "$ref": "#/definitions/constant.InventoryActionType"
                },
                "eventType": {
                    "$ref": "#/definitions/aggregate.StockHistoryEventType"
                },
                "id": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "occurredAt": {
                    "type": "string"
                }
            }
        },
        "aggregate.StockHistoryEventType": {
            "type": "string",
            "enum": [
                "ACTION",
                "STOCK_IN",
                "STOCK_OUT"
            ],
            "x-enum-varnames": [
                "StockHistoryEventTypeAction",
                "StockHistoryEventTypeStockIn",
                "StockHistoryEventTypeStockOut"
            ]
        },
        "constant.InventoryActionType": {
            "type": "string",
            "enum": [
                "PRICE_REDUCTION_PLANNED",
                "TRANSFER_PROPOSED",
                "MARKETING_CAMPAIGN",
                "AWAITING_REVIEW",
                "OTHER"
            ],
            "x-enum-varnames": [
                "InventoryActionTypePriceReductionPlanned",
                "InventoryActionTypeTransferProposed",
                "InventoryActionTypeMarketingCampaign",
                "InventoryActionTypeAwaitingReview",
                "InventoryActionTypeOther"
            ]
        },
        "constant.StockMovementType": {
            "type": "string",
            "enum": [
                "STOCK_IN",
                "STOCK_OUT"
            ],
            "x-enum-varnames": [
                "StockMovementTypeIn",
                "StockMovementTypeOut"
            ]
        },
        "constant.StockStatus": {
            "type": "string",
            "enum": [
                "IN_STOCK",
                "OUT_OF_STOCK"
            ],
            "x-enum-varnames": [
                "StockStatusInStock",
                "StockStatusOutOfStock"
            ]
        },
        "handler.BaseResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.DealershipListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/aggregate.DealershipAggregate"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handler.InventoryActionResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/aggregate.InventoryActionAggregate"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handler.StockHistoryResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/aggregate.StockHistoryEventAggregate"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handler.StockListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/aggregate.InventoryStockListAggregate"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handler.StockResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/aggregate.InventoryStockAggregate"
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handler.ValidationErrItem": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ValidationErrResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ValidationErrItem"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Keyloop Intelligent Inventory API",
	Description:      "Scenario B API for dealership inventory, aging-stock actions, and stock movement history.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
